version: 2

sources:
  - name: olist
    description: Brazilian e-commerce olist dataset
    schema: olist
    tables:
      - name: orders
        description: Customer orders
        columns:
          - name: order_id
            description: Unique identifier for each order
            tests:
              - unique
              - not_null
          - name: customer_id
            description: Identifier for the customer who placed the order
            tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('olist', 'customers')
                    field: customer_id
      - name: order_items
        description: Items included in each order
        columns:
          - name: order_id
            description: Identifier for the order to which the item belongs
            tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('olist', 'orders')
                    field: order_id
      - name: order_payments
        description: Payment information for each order
        columns:
          - name: order_id
            description: Identifier for the order for which payment information is provided
            tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('olist', 'orders')
                    field: order_id
      - name: order_reviews
        description: Reviews for each order
        columns:
          - name: order_id
            description: Identifier for the order being reviewed
            tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('olist', 'orders')
                    field: order_id
      - name: products
        description: Product information
        columns:
          - name: product_id
            description: Unique product identifier
            tests:
              - unique
              - not_null
      - name: customers
        description: Customer information
        columns:
          - name: customer_id
            description: Unique customer identifier
            tests:
              - unique
              - not_null
      - name: sellers
        description: Seller information
        columns:
          - name: seller_id
            description: Unique seller identifier
            tests:
              - unique
              - not_null
      - name: geolocation
        description: Geolocation information
        columns:
          - name: geolocation_zip_code_prefix
            description: Unique geolocation identifier
            tests:
              - unique:
                  config:
                    severity: warn
              - not_null
      - name: product_category_name_translation
