dbt_olist:
  outputs:
    dev:
      type: bigquery
      method: oauth # Or service_account
      project:  "{{ env_var('GOOGLE_PROJECT_ID') }}" # Matches Meltano
      dataset: olist   # Where dbt cleans data
      location: US
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1
  target: dev